name: Generate Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Generate the snake from GitHub contributions
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: themark007
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 2 — Push the generated snake SVG to the 'output' branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
