name: Generate Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Manual trigger

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2 — Generate the snake SVG in dist/
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: themark007
          outputs: dist/github-contribution-grid-snake.svg

      # Step 3 — Push the snake to the output branch
      - name: Push Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
